CATEGORIES_LIST = {
    "Web Browsers": {
        "Chromium",
        "Google Chrome",
        "Vivaldi",
        "Opera",
        "Brave",
        "Zen Browser",
    },
    "Development": {
        "git",
        "vim",
        "emacs",
        "make",
        "cmake",
        "python3-pip",
    },
    "Networking": {
        "curl",
        "wget",
        "net-tools",
        "traceroute",
        "ping",
    },
    "IDEs": {
        "Visual Studio Code",
        "PyCharm",
        "IntelliJ IDEA",
        "Eclipse",
        "Android Studio",
        "WebStorm",
        "Cursor",
    },
    "Multimedia": {
        "Spotify",
        "Discord",
        "VLC",
        "mpv",
        "Audacity",
        "ffmpeg",
    },
    "Terminals": {
        "Kitty",
        "Alacritty",
        "Wezterm",
    },
    "Graphics": {
        "Okular",
        "Scribus",
        "Gimp",
        "Inkscape",
        "Blender",
        "ImageMagick",
    },    
    "System Tools": {
        "Gparted",
        "Disks",
        "Bleachbit",
    },
}