PACKAGE_LIST = {
    "Ubuntu": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
    "Debian": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
    "Fedora": {
        "Git": "sudo dnf install git",
        "Node.js": "sudo dnf install nodejs",
        "Docker": "sudo dnf install docker",
        "Python 3": "sudo dnf install python3",
        "Vim": "sudo dnf install vim",
    },
    "Arch": {
        "Git": "sudo pacman -S git",
        "Node.js": "sudo pacman -S nodejs",
        "Docker": "sudo pacman -S docker",
        "Python 3": "sudo pacman -S python",
        "Vim": "sudo pacman -S vim",
    },
    "openSUSE": {
        "Git": "sudo zypper install git",
        "Node.js": "sudo zypper install nodejs",
        "Docker": "sudo zypper install docker",
        "Python 3": "sudo zypper install python3",
        "Vim": "sudo zypper install vim",
    },
    "Manjaro": {
        "Git": "sudo pacman -S git",
        "Node.js": "sudo pacman -S nodejs",
        "Docker": "sudo pacman -S docker",
        "Python 3": "sudo pacman -S python",
        "Vim": "sudo pacman -S vim",
    },
    "Linux Mint": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
    "Pop!_OS": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
    "Kali Linux": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
    "Zorin OS": {
        "Git": "sudo apt install git",
        "Node.js": "sudo apt install nodejs",
        "Docker": "sudo apt install docker.io",
        "Python 3": "sudo apt install python3",
        "Vim": "sudo apt install vim",
    },
}
