# PACKAGE_LIST = {
#     "Ubuntu": {
#         "Git": 
#             "command: sudo apt install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo apt install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo apt install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo apt install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo apt install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Debian": {
#         "Git": 
#             "command: sudo apt install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo apt install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo apt install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo apt install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo apt install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Linux Mint": {
#         "Git": 
#             "command: sudo apt install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo apt install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo apt install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo apt install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo apt install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Pop!_OS": {
#         "Git": 
#             "command: sudo apt install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo apt install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo apt install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo apt install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo apt install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Zorin OS": {
#         "Git": 
#             "command: sudo apt install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo apt install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo apt install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo apt install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo apt install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Fedora Workstation": {
#         "Git": 
#             "command: sudo dnf install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo dnf install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo dnf install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo dnf install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo dnf install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Nobara": {
#         "Git": 
#             "command: sudo dnf install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo dnf install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo dnf install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo dnf install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo dnf install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",    },
#     "NixOS": {
#         "Git": 
#             "command: nix-env -iA nixpkgs.git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: nix-env -iA nixpkgs.nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: nix-env -iA nixpkgs.docker\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: nix-env -iA nixpkgs.python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: nix-env -iA nixpkgs.vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "openSUSE": {
#         "Git": 
#             "command: sudo zypper install git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo zypper install nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo zypper install docker.io\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo zypper install python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo zypper install vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Manjaro": {
#         "Git": 
#             "command: sudo pacman -S git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo pacman -S nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo pacman -S docker\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo pacman -S python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo pacman -S vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "EndeavourOS": {
#         "Git": 
#             "command: sudo pacman -S git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo pacman -S nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo pacman -S docker\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo pacman -S python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo pacman -S vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
#     "Arch Linux": {
#         "Git": 
#             "command: sudo pacman -S git\n"
#             "description:\n"
#                 "Git is a distributed version control system that tracks changes in source code. "
#                 "On Ubuntu, Git is widely used by developers to collaborate on projects, manage code revisions, and handle branching and merging. "
#                 "After installation, remember to configure your user name and email with Git. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Collaborating on open-source projects\n"
#                 "- Managing personal projects and code histories\n"
#                 "- Integrating with CI/CD pipelines\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `git --version`\n"
#                 "- Basic config: `git config --global user.name 'Your Name'` and `git config --global user.email 'you@example.com'`",
#         "Node.js": 
#             "command: sudo pacman -S nodejs\n"
#             "description:\n"
#                 "Node.js is a JavaScript runtime that allows developers to execute JavaScript outside of the browser. "
#                 "On Ubuntu, it's used for backend development, building APIs, and creating real-time applications. "
#                 "It comes with npm (Node Package Manager) to manage dependencies efficiently. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Server-side web application development\n"
#                 "- Real-time data processing\n"
#                 "- Building scalable network applications\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `node -v`\n"
#                 "- Install npm if needed: `sudo apt install npm`",
#         "Docker":
#             "command: sudo pacman -S docker\n"
#             "description: \n"
#                 "Docker is a containerization platform that packages software and its dependencies into portable containers. "
#                 "On Ubuntu, Docker helps ensure consistency across development, testing, and production environments by isolating applications. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Deploying microservices\n"
#                 "- Simplifying application distribution\n"
#                 "- Streamlining development environments\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `docker --version`\n"
#                 "- Enable and start service: `sudo systemctl enable --now docker`\n"
#                 "- Test run: `sudo docker run hello-world`",
#         "Python 3": 
#             "command: sudo pacman -S python3\n"
#             "description: \n"
#                 "Python 3 is a high-level programming language renowned for its readability and versatility. "
#                 "On Ubuntu, it is used for web development, automation, data analysis, and much more. "
#                 "Its extensive library ecosystem makes Python ideal for both beginners and professionals. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Web development (using frameworks like Django or Flask)\n"
#                 "- Data analysis and machine learning\n"
#                 "- Scripting and automation tasks\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Check version: `python3 --version`\n"
#                 "- Use pip for additional libraries: `sudo apt install python3-pip`",
#         "Vim": 
#             "command: sudo pacman -S vim\n"
#             "description:\n"
#                 "Vim is a highly efficient text editor that operates within the terminal, offering powerful editing and customization features. "
#                 "On Ubuntu, Vim is favored by programmers and system administrators for its speed and extensive plugin ecosystem. "
#                 "\n\n🔹 Common Use Cases:\n"
#                 "- Code editing and scripting\n"
#                 "- Remote server administration\n"
#                 "- Quick file edits\n"
#                 "\n⚡ Extra Notes:\n"
#                 "- Open Vim: `vim filename`\n"
#                 "- Save and exit: press `Esc` then type `:wq`\n"
#                 "- Learn the basics with `vimtutor`",
#     },
# }

PACKAGE_DETAILS = {
    "Web Browsers": {
        "Chromium": 
            "command: sudo apt install chromium-browser\n"
            "description:\n"
                "Chromium is an open-source web browser project that serves as the base for Google Chrome. "
                "It provides a fast and secure browsing experience while maintaining a high level of customizability. "
                "\n\n🔹 Common Use Cases:\n"
                "- Secure and private web browsing\n"
                "- Testing web applications on an open-source browser\n"
                "- Running lightweight browser-based applications\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `chromium-browser`\n"
                "- Check version: `chromium-browser --version`",
        "Google Chrome":
            "command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo dpkg -i google-chrome-stable_current_amd64.deb\n"
            "description:\n"
                "Google Chrome is a fast and widely used web browser known for its performance, security, and extensive extension support. "
                "It is popular among developers and casual users alike due to its seamless Google service integration. "
                "\n\n🔹 Common Use Cases:\n"
                "- Web browsing with extensive extension support\n"
                "- Syncing across multiple devices\n"
                "- Developer-friendly tools for web development\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `google-chrome`\n"
                "- Incognito mode: `google-chrome --incognito`",
        "Vivaldi":
            "command: wget -qO- https://downloads.vivaldi.com/stable/vivaldi-stable_amd64.deb | sudo dpkg -i\n"
            "description:\n"
                "Vivaldi is a privacy-focused and highly customizable web browser with built-in features like a notes manager, screenshot tool, and tab stacking. "
                "It offers a unique browsing experience tailored to power users. "
                "\n\n🔹 Common Use Cases:\n"
                "- Privacy-focused web browsing\n"
                "- Multi-tab organization and productivity tools\n"
                "- Built-in customization and theming options\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `vivaldi`\n"
                "- Enable dark mode: `vivaldi --force-dark-mode`",
        "Opera": 
            "command: wget -qO- https://download3.operacdn.com/pub/opera/desktop/109.0.5097.41/linux/opera-stable_109.0.5097.41_amd64.deb | sudo dpkg -i -\n"
            "description:\n"
                "Opera is a fast and feature-rich web browser with a built-in VPN, ad blocker, and sidebar integrations for chat apps like WhatsApp and Messenger. "
                "It offers a clean user interface, customizable workspaces, and speed optimizations for modern browsing. "
                "\n\n🔹 Common Use Cases:\n"
                "- Secure and private browsing with the built-in VPN\n"
                "- Accessing chat applications directly from the browser sidebar\n"
                "- Using built-in ad-blocking for faster page loads\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `opera`\n"
                "- Enable VPN: Go to `Settings > Privacy & Security > Enable VPN`\n"
                "- Speed Dial: Customize homepage shortcuts with `opera://startpage`",
        "Brave": 
            "command: sudo apt install curl && curl -fsSL https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo tee /usr/share/keyrings/brave-browser-archive-keyring.gpg > /dev/null && "
            "echo 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main' | sudo tee /etc/apt/sources.list.d/brave-browser-release.list && "
            "sudo apt update && sudo apt install brave-browser\n"
            "description:\n"
                "Brave is a privacy-focused web browser designed to block ads and trackers by default. "
                "It features a built-in Tor mode for anonymous browsing, Brave Rewards for earning cryptocurrency through privacy-friendly ads, and strong security measures. "
                "\n\n🔹 Common Use Cases:\n"
                "- Private browsing with built-in ad and tracker blocking\n"
                "- Anonymous browsing with Brave's built-in Tor window\n"
                "- Earning cryptocurrency (BAT) through Brave Rewards\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `brave-browser`\n"
                "- Open in private mode: `brave-browser --incognito`\n"
                "- Enable Tor mode: Open a new private window with Tor via `Menu > New Private Window with Tor`",
        "Zen Browser": 
            "command: (No official package; download manually from https://zenbrowser.com)\n"
            "description:\n"
                "Zen Browser is a lightweight, privacy-oriented browser focused on minimalism and distraction-free browsing. "
                "It is designed for users who prioritize simplicity, security, and low system resource usage. "
                "\n\n🔹 Common Use Cases:\n"
                "- Minimalist browsing with a clutter-free interface\n"
                "- Privacy-focused web surfing with minimal tracking\n"
                "- Low resource consumption for improved performance on older hardware\n"
                "\n⚡ Extra Notes:\n"
                "- No official Linux package; use AppImage or install manually from their website\n"
                "- Check settings for customization options like dark mode and script blocking",
    },

    "Development": {
        "git":
            "command: sudo apt install git\n"
            "description:\n"
                "Git is a distributed version control system that tracks changes in source code, enabling collaboration and efficient project management. "
                "It is a must-have tool for developers working in teams. "
                "\n\n🔹 Common Use Cases:\n"
                "- Managing source code repositories\n"
                "- Collaborative software development with version control\n"
                "- Handling branching and merging in projects\n"
                "\n⚡ Extra Notes:\n"
                "- Check version: `git --version`\n"
                "- Configure: `git config --global user.name 'Your Name'`",
        "vim":
            "command: sudo apt install vim\n"
            "description:\n"
                "Vim is a highly customizable text editor built for efficiency and speed. "
                "It is widely used for programming, scripting, and server administration. "
                "\n\n🔹 Common Use Cases:\n"
                "- Fast and efficient text editing\n"
                "- Remote server administration\n"
                "- Writing scripts and configuration files\n"
                "\n⚡ Extra Notes:\n"
                "- Open a file: `vim filename`\n"
                "- Exit: Press `Esc`, then type `:q!` to quit without saving or `:wq` to save and exit.",
        "Emacs": 
            "command: sudo apt install emacs\n"
            "description:\n"
                "Emacs is a powerful, extensible, and customizable text editor that serves as an IDE, file manager, email client, and more. "
                "It supports thousands of extensions, making it highly versatile for programming, note-taking, and system administration. "
                "\n\n🔹 Common Use Cases:\n"
                "- Writing and editing code with built-in syntax highlighting\n"
                "- Using `org-mode` for efficient note-taking and project management\n"
                "- Running shell commands and managing files without leaving Emacs\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `emacs`\n"
                "- Exit Emacs: Press `Ctrl + X` then `Ctrl + C`\n"
                "- Open tutorial: Run `emacs` and type `Ctrl + H` then `T`\n"
                "- Use Evil Mode for Vim keybindings: `M-x package-install RET evil RET`",      
        "Make": 
            "command: sudo apt install make\n"
            "description:\n"
                "Make is a build automation tool used to compile and link programs efficiently. "
                "It processes `Makefile` instructions to determine which parts of a program need recompiling and executes only the necessary tasks. "
                "\n\n🔹 Common Use Cases:\n"
                "- Automating software compilation and project builds\n"
                "- Running predefined workflows in `Makefile`\n"
                "- Managing dependencies in large projects\n"
                "\n⚡ Extra Notes:\n"
                "- Check version: `make --version`\n"
                "- Run Makefile: `make`\n"
                "- Debug Makefile execution: `make --debug=v`",       
        "CMake": 
            "command: sudo apt install cmake\n"
            "description:\n"
                "CMake is a cross-platform build system generator that simplifies project compilation across multiple environments. "
                "It automates the process of generating Makefiles or project files for compilers like GCC, Clang, and MSVC. "
                "\n\n🔹 Common Use Cases:\n"
                "- Generating Makefiles or Ninja build scripts\n"
                "- Managing multi-platform build configurations\n"
                "- Compiling C/C++ projects with ease\n"
                "\n⚡ Extra Notes:\n"
                "- Check version: `cmake --version`\n"
                "- Generate Makefile: `cmake .`\n"
                "- Build project: `cmake --build .`\n"
                "- Clean build files: `rm -rf CMakeCache.txt CMakeFiles`", 
        "Python3-pip": 
            "command: sudo apt install python3-pip\n"
            "description:\n"
                "pip is the package manager for Python that simplifies the installation, upgrading, and removal of Python libraries. "
                "It allows developers to easily manage dependencies and install packages from the Python Package Index (PyPI). "
                "\n\n🔹 Common Use Cases:\n"
                "- Installing Python libraries for development (e.g., `pip install requests`)\n"
                "- Managing virtual environments and dependencies\n"
                "- Automating software installations for Python-based projects\n"
                "\n⚡ Extra Notes:\n"
                "- Check version: `pip3 --version`\n"
                "- Install a package: `pip3 install package_name`\n"
                "- List installed packages: `pip3 list`\n"
                "- Upgrade pip: `pip3 install --upgrade pip`",
    },

    "Networking": {
        "curl":
            "command: sudo apt install curl\n"
            "description:\n"
                "cURL is a command-line tool for transferring data using various network protocols such as HTTP, HTTPS, FTP, and more. "
                "It is commonly used for API interactions, file downloads, and debugging network issues. "
                "\n\n🔹 Common Use Cases:\n"
                "- Downloading files from a remote server\n"
                "- Testing APIs and web requests\n"
                "- Fetching web pages via command-line\n"
                "\n⚡ Extra Notes:\n"
                "- Fetch URL: `curl https://example.com`\n"
                "- Save output: `curl -o file.html https://example.com`",
    },

    "IDEs": {
        "Visual Studio Code":
            "command: sudo snap install code --classic\n"
            "description:\n"
                "VS Code is a lightweight yet powerful code editor with built-in Git support, debugging tools, and an extensive extension marketplace. "
                "It is widely used for software development across multiple languages. "
                "\n\n🔹 Common Use Cases:\n"
                "- Developing applications in multiple programming languages\n"
                "- Debugging and running code efficiently\n"
                "- Using extensions for enhanced functionality\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `code`\n"
                "- Install extensions from the marketplace.",
    },

    "Multimedia": {
        "VLC":
            "command: sudo apt install vlc\n"
            "description:\n"
                "VLC is an open-source, cross-platform media player that supports a wide variety of audio and video formats. "
                "It is known for its ability to play almost any media file. "
                "\n\n🔹 Common Use Cases:\n"
                "- Playing audio and video files\n"
                "- Streaming media from online sources\n"
                "- Converting media file formats\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `vlc`\n"
                "- Convert files: `vlc -I dummy input.mp4 --sout='#transcode{vcodec=h264}:std{access=file,dst=output.mp4}' vlc://quit`",
    },

    "Terminals": {
        "Kitty":
            "command: sudo apt install kitty\n"
            "description:\n"
                "Kitty is a fast, feature-rich terminal emulator with GPU acceleration and advanced text rendering. "
                "It is highly customizable and supports tabs, splits, and scripting. "
                "\n\n🔹 Common Use Cases:\n"
                "- Running shell commands efficiently\n"
                "- Handling multiple terminal tabs/splits\n"
                "- Using hardware acceleration for faster rendering\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `kitty`\n"
                "- Customize config: `~/.config/kitty/kitty.conf`",
    },

    "Graphics": {
        "Gimp":
            "command: sudo apt install gimp\n"
            "description:\n"
                "GIMP (GNU Image Manipulation Program) is a powerful open-source image editor, comparable to Photoshop. "
                "It is used for photo retouching, image composition, and graphic design. "
                "\n\n🔹 Common Use Cases:\n"
                "- Editing and retouching images\n"
                "- Creating digital artwork and graphics\n"
                "- Designing UI elements\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `gimp`\n"
                "- Supports plugins and scripting with Python.",
    },

    "System Tools": {
        "Gparted":
            "command: sudo apt install gparted\n"
            "description:\n"
                "GParted is a powerful partition manager that allows users to create, resize, and manage disk partitions. "
                "It is widely used for disk maintenance and system recovery. "
                "\n\n🔹 Common Use Cases:\n"
                "- Resizing and formatting disk partitions\n"
                "- Managing disk space efficiently\n"
                "- Troubleshooting and repairing storage devices\n"
                "\n⚡ Extra Notes:\n"
                "- Launch: `gparted`\n"
                "- Requires root privileges to modify partitions.",
    },
}
